### ISSUE TITLE
"select entry type"  display not expanding properly

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#11589]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux 6.8.0-39-generic amd64  LinuxMint and Cinnamon, latest

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.16--2024-08-04--db9f83c
Linux 6.8.0-39-generic amd64 
Java 21.0.2 
JavaFX 22.0.2+4

1. ctrl+n to open "select entry type" window
2. try to select from "others"
3. can't scroll to entry types not displayed
4. drag window border slightly
5. can see more entry types

Video below shows a separate problem too: preview tab is full of rubbish.

https://github.com/user-attachments/assets/84de2ea7-1a0a-42a7-ac8b-1313bc4c0e2e

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
I think this is a duplicate of https://github.com/JabRef/jabref/issues/10729 and this bug https://bugs.openjdk.org/browse/JDK-8324423

You can test a version with javafx23 from here https://builds.jabref.org/jdk-ea/

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by ThiloteE** [comment]
JabRef 6.0alpha4
Windows 10 10.0 amd64 
Java 25.0.1 
JavaFX 25.0.2+4

The workaround was to increase the size of the window, but nowadays the window again doesn't open large enough by default, thereby some entry types are now showing under non-standard types.


How it is
<img width="596" height="756" alt="Image" src="https://github.com/user-attachments/assets/9df1e290-3d51-4b33-8ff0-b76d924e6246" />


How it should be:
<img width="876" height="724" alt="Image" src="https://github.com/user-attachments/assets/ea4b339a-aa11-4695-a818-33a6c7408aed" />

**Comment by Phaneendra2005** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by pluto-han** [comment]
This issue still exists in `main`

<img width="872" height="867" alt="Image" src="https://github.com/user-attachments/assets/4d68a903-02e1-4c71-ba70-775d815176e7" />

**Comment by pluto-han** [comment]
@f0restron07 You can start working on this issue

**Comment by cmarqueslau** [comment]
Hi! I am actively working on this issue. Could you please add the 📌 Pinned label so it doesn't get unassigned? Thanks!

**Comment by koppor** [comment]
> Hi! I am actively working on this issue. Could you please add the 📌 Pinned label so it doesn't get unassigned? Thanks!

You can submit a draft PR within four days. This should be possible if you work "actively" on this 😅🥂. Nevertheless, I added "Pinned"
