### ISSUE TITLE
"\'{}" Escape Sequence Does Not Display Correctly in Entry Preview

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2498]
JabRef 3.8.2
windows 10 10.0 amd64 
Java 1.8.0_121

Steps to reproduce:

1. Create a new entry with "Pie{\\'{n}}kowski, G." as author.
2. The author name is correctly displayed as Pieńkowski in the author column of the entry table. This was a fix for https://github.com/JabRef/jabref/issues/2458 introduced in JabRef 3.8.2
3. The author name, however, is NOT correctly displayed in the entry preview of the article. Instead it is shown as Pieŉkowski, G.

Somewhat similar issues have been reported here:
https://github.com/JabRef/jabref/issues/2458
https://github.com/JabRef/jabref/issues/2460

**Comment by lenhard** [comment]
I pushed a fix and a working version is available at http://builds.jabref.org/fix-latex-free-entry-preview/

@AEgit can you give it a try and confirm if this works for you?

**Comment by AEgit** [comment]
Thank you very much! Yes, indeed it works now.

For now I'll continue using the old master 3.8.2, as the groups panel in the new version does not seem to be complete (e.g., I cannot expand all groups automatically and the groups are not highlighted when an associated article is selected) - I have to say, however, that the new JavaFX version of the groups panel looks nice ;)
I can confirm, however, that the abovementioned bug has been fixed in:
JabRef 4.0.0-dev--snapshot--2017-01-30--fix-latex-free-entry-preview--cdbc2ead0

Once the groups panel is complete, I will completely switch over.
Great job!

**Comment by lenhard** [comment]
@AEgit Indeed, the groups panel is under construction now and will be completed for the next release.

However, it seem that we cannot use the version that you tested. The problem is the following: There are a lot of formatters that you can specify for the entry preview and doing a LaTeX to unicode conversion by default will break some of them. For instance, it conflicts with a LaTeX to HTML conversion (which is possible currently). Therefore, you will need to configure the preview layout yourself. Fortunately, this is very easy. Just go to Preferences -> Entry Preview and add `LatexToUnicode` to the fields where you need the conversion. As an example, my configuration which works for the example you specified above looks like this:
```
\begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars,LatexToUnicode]{\author}<BR>\end{author}
```
I'll close this issue and the connected PR as invalid.

**Comment by AEgit** [comment]
@lenhard: Hmmm, I've modified the Entry Preview for JabRef 3.8.2 according to your example, but I still get the same problem:

\begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars,LatexToUnicode]{\author}<BR>\end{author}

 "Pie{\\'{n}}kowski, G." is displayed as "Pieŉkowski, G."
I mean, I don't mind this issue that much, so if it is impossible/difficult to fix it, I guess everyone can live with it. But I just wanted to make sure that everyone was aware of it.

**Comment by lenhard** [comment]
@AEgit Sorry, this was my fault again. When I checked, I had the second layout style selected... The `HTMLChars` and `LatexToUnicode` formatters conflict with each other. This should work, hopefully:

```
\begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),LatexToUnicode]{\author}<BR>\end{author}
```

**Comment by AEgit** [comment]
This does work, indeed, thank you very much!

**Comment by tobiasdiez** [comment]
@lenhard should we update the default entry preview accordingly?

**Comment by lenhard** [comment]
@tobiasdiez Not sure (since I do not really use it) what people want more. The HTML conversion of the latex free version. Asked personally, I would do nothing, but maybe somebody else has a stronger opinion on the best preview configuration.

**Comment by AEgit** [comment]
I would prefer to see the default changed (but that is just my personal opinion). Maybe we should create a poll?

**Comment by lenhard** [comment]
@AEgit Good idea :-) Can I count on your help again? Could you create a poll at http://discourse.jabref.org/ that asks if people rather want a conversion to HTML characters or to Unicode in the preview panel?

**Comment by AEgit** [comment]
Done ;)

http://discourse.jabref.org/t/change-of-default-of-entry-preview/446
