### ISSUE TITLE
Incorrect display in the author entry column

### ISSUE THREAD

**Issue by bvdalen** [JabRef/jabref#2652]
Version 3.8.2, confirmed in JabRef 4.0.0-dev--snapshot--2017-03-16--master--4323923a8, Windows 7 6.1 amd64 and Java 1.8.0_92.

The below BibLaTeX file illustrates the following problems in JabRef's display of the author entry column:

1. The single name "Rodriguez Fernandez, José María" in Item:1 is turned into two authors F. Rodriguez and J. María. This does not happen in the alternative format in Item:2, nor in combination with another author in either format (Item:3 and Item:4).

2. In the format "Waard, Gerard de" the prefix "de" is abbreviated as "d." and comes at the end of the name as displayed in the author column, but in the alternative equivalent format "Gerard de Waard" it is not abbreviated and appears at the beginning (but is correctly ignored in sorting). I think the latter display form is preferable, but in any case it reads easier if the prefix is not abbreviated.

3. Besides the prefix "de" also the first of a double surname seems to be ignored in sorting the author column for certain (but not all) input formats: Item:2 and Item:3 are apparently sorted in under F, but item:4 correctly under R.

Sample BibLaTeX file:
```
% Encoding: UTF-8

@Article{Item:1,
  author    = {Rodriguez Fernandez, José María},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:2,
  author    = {José María {Rodriguez Fernandez}},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:3,
  author    = {José María {Rodriguez Fernandez} and Millás Vallicrosa, José María},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:4,
  author    = {Rodriguez Fernandez, José María and Millás Vallicrosa, José María},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:5,
  author    = {Waard, Gerard de},
  title     = {Jabref's Issues},
  date      = {2017},
}

@Article{Item:6,
  author    = {Gerard de Waard},
  title     = {Jabref's Issues},
  date      = {2017},
}

@Article{Item:7,
  author    = {José Martinez},
  title     = {Jabref's Issues},
  date      = {2017},
}

@Comment{jabref-meta: databaseType:biblatex;}
```

**Comment by Maformatiker** [comment]
I think the second point is not a bug. The two possible formats are de Waard, Gerard and Gerard de Waard.
Contrary to this, the first point is obviously wrong. Braces do not have an influence on the output. However they change the behaviour of the automatic key generator. While "Rinnooy Kan, Alexander H. G." results in "KAH" (for authorAlpha), "{Rinnoy Kan}, Alexander H G" is translated to "RKan".

**Comment by bvdalen** [comment]
Many thanks for looking at this!
On point 2: I would expect that the two equivalent formats de Waard, Gerard and Gerard de Waard should lead to the same output in the entry column "author" (as they would in a BibLaTeX bibliography created from a JabRef database).
On point 1: According to the BibLaTeX manual of 20/4/2015, Section 2.3.3, p. 31, a corporate author needs to be enclosed between an extra set of bracelets. I thought I had seen the same suggestion for a double surname, but cannot find this anymore. But this was how I have consistently used the bracelets, and at least up to JabRef 2.11 this was also treated in the entry column exactly as I expected.

**Comment by Maformatiker** [comment]
Hello bvdalen,

On point 2: I am not sure what you want to say. For me the two formats "de Waard, Gerard" and "Gerard de Waard" lead to the same output. In your original post you compared this to the output of "Waard, Gerard de", which leads to an interpretation of "de" as first name. I think, that's ok.

On point 1: At least, according to what is written in the javadoc of the class [AuthorList](https://github.com/Maformatiker/jabref/blob/master/src/main/java/org/jabref/model/entry/AuthorList.java) one does not need to use braces for a double surname

> one comma: 'junior-part' is empty, 'first-part' consists of all tokens
> after comma, 'von-part' consists of the longest sequence of lower-case tokens
> in the very beginning, 'last-part' consists of all tokens after 'von-part'
> and before comma; note that any part can be empty; for example: in "de la
> Vall{\'e}e la Poussin, Charles Louis Xavier Joseph", 'first-part'="Charles
> Louis Xavier Joseph", 'von-part'="de la", 'last-part'="Vall{\'e}e la
> Poussin"; in "Joseph de la Vall{\'e}e la Poussin, Charles Louis Xavier",
> 'first-part'="Charles Louis Xavier", 'von-part'="", 'last-part'="Joseph de la
> Vall{\'e}e la Poussin";

**Comment by bvdalen** [comment]
Hi Maformatiker,

Sorry, I was mistaken on point 2. I somehow assumed that the prefix may (also) follow the first name in the format "surname, firstname".
Concerning the use of bracelets, I guess the question is whether "José María {Rodriguez Fernandez}" is a valid alternative to "Rodriguez Fernandez, José María", i.e. whether {Rodriguez Fernandez} is interpreted together as the surname. In versions 2.11 and the current 4.0 master this seems to be the case both for the display in the "author" column and when I export the entry, in version 3.8 the export was ok but the "author" column displayed Fernandez, J. M. R. 
So I guess #2 is not a bug, #1 is, and #3 depends on whether "José María {Rodriguez Fernandez}" is a valid format?

**Comment by Maformatiker** [comment]
I commented on this topic on the page of my proposed changes. #2669

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by bvdalen** [comment]
Hi Christoph,

Many thanks for your and the others' efforts.
I have only briefly checked the current developer version since I am on 
vacation. It seems that issue 1 has been resolved, issue 2 never was 
one, but issue 3 may still be a problem: in the format "José María 
{Rodriguez Fernandez}" this name is still sorted in under F rather than 
under R.
I am still not certain whether the above format is supposed to be a 
valid alternative for "Rodriguez Fernandez, José María", but it used to 
work correctly in earlier versions and in displaying the name in the 
author/editor column in the current version, only not in sorting the 
author/editor column.

Benno


Op 21-4-2017 om 14:59 schreef Christoph:
