### ISSUE TITLE
JabRef-4.0.0-dev--snapshot--2017-05-18--master--018173ebd.jar  not displaying editing fields

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2851]
JabRef version 4.0.0-dev of 18 May on Linux Mint Cinnamon 18.1 (=Ubuntu 16.04)

Steps to reproduce:

1. open JabRef (java -jar ...)
2. select an entry and double-click it
3. the field tabs display, but the area where the fields would be is all grey

This issue is sporadic :-(   

It seems to happen reproducibly when I try to edit this entry:

@Book{maas+wuja-orig-redacted,
  author     = {{[Name redacted]}},
  title      = {The Original Āsanas of Yoga},
  pubstate   = {inpreparation},
  annotation = {http://www.cardiff.ac.uk/share/research/centres/chra/whatwedo/journal-asian-lit-and-translation.html Work in progress. It is planned to submit the finished article to the journal \emph{Asian Literature and Translation: A Journal of Religion and Culture} for consideration. The article will also appear at academia.edu},
  file       = {:/home/dom/Dropbox/CurrentWork/Asanas/asanas.pdf:PDF},
  issn       = {2051-5863},
  owner      = {dom},
  timestamp  = {2014.03.12},
}

and every entry after that.

```
Help/View event log doesn't work
```
![screenshot from 2017-05-18 09-01-55](https://cloud.githubusercontent.com/assets/762246/26215897/5040f34c-3bbf-11e7-8afc-59c98b270f6c.png)

**Comment by bernhard-kleine** [comment]
I had a similar issues with the previous snapshot, however, going to the {} biblatex source and back to Required fields made the fields visible, but I took quite some time. My desktop is not the fastest but really fast.

**Comment by Doc73** [comment]
Same issue: #2843

**Comment by despresT** [comment]
I have the same issue using Xubuntu 17.04 (= to Ubuntu 17.04) with the last version of JabRef: JabRef-4.0.0-dev--snapshot--2017-05-20--master--01e854829.jar
However, for me, this happen all the time, even if I go fisrt in the {}biblatex source and go back to the fields, they are still invisible.

The Files annotations, Related articles and {} Source BibTex are the only working field.

**Comment by ninfito** [comment]
I have the same issue on OpenSuse 13.2 (jre1.8.0_131), JabRef-4.0.0-dev--snapshot--2017-05-23--master--6db383443.jar. 

It seems to happen when I try to edit a item and that PDF file doesn't exist. 

@Article{AuthorYear,
....
file = {:/home/user/Dropbox/OLD_FILE_DELETED.pdf:PDF},
....
}
@JabRef/developers

**Comment by lenhard** [comment]
@wujastyk @bernhard-kleine @Doc73 @despresT @ninfito @Siedlerchr We believe that we have fixed this issue. Can you please try out the fix here: http://builds.jabref.org/fixEntryEditor/ and report if it works for you?

**Comment by Doc73** [comment]
Thanks! It's working!

There is a small delay between the click on the bibliographic item and the appearance of entries in the editor, but it works very well.

**Comment by tobiasdiez** [comment]
Perfect! Thanks for the feedback. The fixed version is now merged into master and can be downloaded as usual from http://builds.jabref.org/master/.

**Comment by bernhard-kleine** [comment]
Editing in the editor -> Optinal fields is still hampered by the fact that no scrolling in the editor window is possible, https://github.com/JabRef/jabref/issues/2847

**Comment by Siedlerchr** [comment]
@tobiasdiez  I can confirm the working, but however, I still get the above listed exceptions on Xubuntu 16.x, with a  desktop resolution of 2560x1440 (27")
```

java.lang.IllegalArgumentException: WIDTH * HEIGHT is too large
	at com.sun.pisces.AbstractSurface.<init>(AbstractSurface.java:43)
	at com.sun.pisces.JavaSurface.<init>(JavaSurface.java:37)
	at com.sun.prism.sw.SWRTTexture.<init>(SWRTTexture.java:51)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:135)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:124)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: WIDTH * HEIGHT is too large
	at com.sun.pisces.AbstractSurface.<init>(AbstractSurface.java:43)
	at com.sun.pisces.JavaSurface.<init>(JavaSurface.java:37)
	at com.sun.prism.sw.SWRTTexture.<init>(SWRTTexture.java:51)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:135)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:124)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: WIDTH * HEIGHT is too large
	at com.sun.pisces.AbstractSurface.<init>(AbstractSurface.java:43)
	at com.sun.pisces.JavaSurface.<init>(JavaSurface.java:37)
	at com.sun.prism.sw.SWRTTexture.<init>(SWRTTexture.java:51)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:135)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:124)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: WIDTH * HEIGHT is too large
	at com.sun.pisces.AbstractSurface.<init>(AbstractSurface.java:43)
	at com.sun.pisces.JavaSurface.<init>(JavaSurface.java:37)
	at com.sun.prism.sw.SWRTTexture.<init>(SWRTTexture.java:51)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:135)
	at com.sun.prism.sw.SWResourceFactory.createRTTexture(SWResourceFactory.java:124)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ninfito** [comment]
[JabRef-4.0.0-dev--snapshot--2017-05-30--fixEntryEditor--b536509f4.jar]

It's working. Thanks.

As noted by @Doc73, there is a small delay between the click on the bibliographic item and the appearance of entries in the editor, but this delay is accumulated by scrolling through several items, for example, by pressing the Up Arrow key or Page Up key. This delay can be more than 45 seconds in a database of less than 200 items.

@tobiasdiez, this is, maybe, a new issue?

**Comment by wujastyk** [comment]
Same here.  Short delay for the fields to appear, but then all's fine.
Thanks!

D
​ominik
​
