### ISSUE TITLE
Problem with shortcut for opening settings on Mac

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#3127]
JabRef version 3.8.2 on Mac OS X 10.12

When using the shortcut "cmd+," to open the settings (which is usually the default one on Mac), it does it but it also marks the current selected entry. 

I checked the keybinding in Jabref and the shortcut for marking entries is "cmd+m" and it works. And there is no option to manage the shortcut for opening the settings.

**Comment by Siedlerchr** [comment]
Hi,
could you please test this with the current JabRef 4.0? 
https://builds.jabref.org/master

**Comment by PierreMarchand20** [comment]
Well this time, it marks the current selected entry but it does not open the settings. ( I used JabRef-4.0-dev--snapshot--2017-08-18--master--42c39cb0c.jar to test)

By the way, testing the last version deleted all my groups ...

**Comment by Siedlerchr** [comment]
You can change the keybinding for mark entries under Options->Customize Keybindings -> Edit
There is no specific shortcut for opening the settings. Under Windows I can use Alt to show the mnemonic keys of the menu items and then hit alt+o for opening options and then alt+p for preferences.
@lynyus  Do you already have your mac? 

Regarding your groups: The group format changed with JabRef 4.0 meaning, that you can no longer use them in JabRef v 3.8.2, but they should not got deleted. JabRef 4.0 should have imported them correctly.

**Comment by PierreMarchand20** [comment]
Ok, I did not know about this change of format for the groups, is there a thread about it ? it is a real problem then... should I post another issue about it ?

Regarding how to manage the shortcut, as I said, I looked at it and I was surprised to see that "cmd+," was not used but worked to open the settings in 3.8.2 and to mark an entry.

**Comment by Siedlerchr** [comment]
Hi,
I would file the option to open the settings with `cmd+,` as an enhancement.

Regarding the groups we had the [release announcement](https://blog.jabref.org/#april-17-2017-%E2%80%93-jabref-4-0-is-on-the-way-%E2%80%93-beta-version-release) and there was an issue which should have been already fixed since a long time.

If the group problem still persists I would ask you to add a new issue with as many details possible.
And please also open the bib file with an text editor to see if the group info is still there.

**Comment by PierreMarchand20** [comment]
Hi,
This would be a nice enhancement indeed, and it would be nice to have some reasonable default value like "cmd+," on Mac for example.

I tried the last version of JabRef 4.0 and I have no more issues with groups.

But, there is still an issue with 3.8.2 AND 4.0 about "cmd+,", it marks the selected entry when it should not, since the shortcut is "cmd+M".

**Comment by chochreiner** [comment]
The MacAdapter does not seam to work as it used to for the Swing application.
This is why the MacOs specific shortcuts do not work anymore
There is actually already a [FeatureRequest](https://bugs.openjdk.java.net/browse/JDK-8091683) on this topic for the JDK, but I guess it has a rather low priority.

**Comment by stefan-kolb** [comment]
Thanks for your report.! We recently migrated the UI of JabRef to JavaFX. Therefore, we need to reevaluate all issues targeting the old Swing UI. Feel free to reopen, if the problem persists with the new JavaFX UI.
Download the current development version at http://builds.jabref.org/master/
