### ISSUE TITLE
Focus on an entry lost when selecting a group even if the entry is within the group

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3367]
JabRef 4.1-dev--snapshot--2017-10-16--master--ebf39a431
Windows 7 6.1 amd64 
Java 1.8.0_144

Steps to reproduce:

1. open a database 
2. select an entry which is grouped
3. select the group and you will notice that the focus is lost.

This is totally unexpected. 
The same is obvious when you select an entry within a group and you change back to the supergroup all groups. The focus is lost as well. Please explain to me why this is the preferred way with Jabref. The focus on an entry should only be lost when you select a group in which the selected entry is not.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.

**Comment by bernhard-kleine** [comment]
Could I be noted when this is merged with the master? Please, I donot want to test too many jabref versions in parallel. But I will eagerly use a new master.

**Comment by tobiasdiez** [comment]
You can subscribe to https://github.com/JabRef/jabref/pull/3621 (there is a button on the right) so that you get a notification about the recent progress.

**Comment by Siedlerchr** [comment]
The migration of the maintable is a huge step and we want to make sure that  this is stable on all systems before we merge it in the master

**Comment by DOFfactory** [comment]
JabRef 5.0-dev--snapshot--2018-11-11--master--50875f967
Windows 10 10.0 amd64 
Java 1.8.0_172

I can second this, this still happens on v5.0. Sometimes the focus is lost and shows the previous searched/selected entry, especially if a new entry has been generated via DOI search. So irritating!
