### ISSUE TITLE
When drag and drop to copy pdf folder is created

### ISSUE THREAD

**Issue by teun95** [JabRef/jabref#4087]
JabRef 4.3-dev--snapshot--2018-05-28--master--bf7fb5168
Linux 4.14.47-1-manjaro amd64 
Manjaro GNOME Edition (17.1.10)
Java 1.8.0_172

When I drop a pdf file on a reference and attach it, a folder is attached with the chosen name instead of the file. This only happens when choosing to copy the pdf, moving works as expected.

Steps to reproduce:

1. Drag PDF to reference from nautilus 
2. Choose "only attach PDF"
3. Choose "copy file to directory" and accept the suggested renaming
4. Accept the following popup
5. There is a folder in the default pdf location with the name of the pdf file. In jabjref it looks like a pdf is attached, but opening it results in an error as expected.

<details>
  <summary>Log File</summary>
  
  ```
21:12:07.156 [JabRef CachedThreadPool] ERROR org.jabref.logic.util.io.FileUtil - Copying Files failed.
java.nio.file.FileSystemException: /mnt/3TB/cloud/username/Work/Academicmaterial/jabref/Goldgeier2001.pdf: Is a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_172]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_172]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_172]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_172]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_172]
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_172]
	at java.nio.file.Files.write(Files.java:3292) ~[?:1.8.0_172]
	at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:164) ~[Jabref.jar:?]
	at org.jabref.gui.externalfiles.DroppedFileHandler.doCopy(DroppedFileHandler.java:559) ~[Jabref.jar:?]
	at org.jabref.gui.externalfiles.DroppedFileHandler.linkPdfToEntry(DroppedFileHandler.java:207) ~[Jabref.jar:?]
	at org.jabref.gui.externalfiles.DroppedFileHandler.linkPdfToEntry(DroppedFileHandler.java:174) ~[Jabref.jar:?]
	at org.jabref.pdfimport.PdfImporter.importPdfFilesInternal(PdfImporter.java:134) ~[Jabref.jar:?]
	at org.jabref.pdfimport.PdfImporter.importPdfFiles(PdfImporter.java:88) ~[Jabref.jar:?]
	at org.jabref.gui.groups.EntryTableTransferHandler.lambda$handleDraggedFiles$0(EntryTableTransferHandler.java:306) ~[Jabref.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
  ```
</details>

**Comment by wilthan** [comment]
Yes, we just noticed the same issue.
When you move the file then everything works as expected, when you copy the file then the file is not actually moved but a folder with the file name is created.

**Comment by Siedlerchr** [comment]
Refs #3765

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by wilthan** [comment]
I just installed the dev version JabRef_windows-x64_5_0-dev--snapshot--2018-08-20--master--cf3fab884, and tried to drag and drop a pdf file onto a reference. Drag and drop does not work and so I couldn't test if the actual issue with the created folder when you copy a pdf file is resolved

**Comment by Siedlerchr** [comment]
Where exactly did you drop the pdf file?
Note that the default behavior of JabRef changed. Dropping on the main table will try to create an entry from the pdf.
Dragging on the entry preview or general tab should move the file to the file dir

**Comment by teertinker** [comment]
Hey,
I am using Jabref 4.3.1 and the problem still exists. As described, it appears only when I use the copy option.

JabRef 4.3.1
Ubuntu 14.04
Linux 4.4.0-131-generic amd64 
Java 1.8.0_181

**Comment by Siedlerchr** [comment]
@teertinker  Please use the latest development version 5.x http://builds.jabref.org/master/

**Comment by luca-san-git** [comment]
I am sorry for commenting on such an old thread, but I have the same problem. Version 4.3 creates an empty folder, and after downloading the new (development) version 5.0 I am not able anymore to create a new entry just by drag and drop.

I've read this, but I don't know what is the "main table" apparently: 

> Dropping on the main table will try to create an entry from the pdf.
Dragging on the entry preview or general tab should move the file to the file dir

 Where should I drop the file? It only accept it on an existing article entries, and it merely links that entry with a copy created in the Jabref folder.
