### ISSUE TITLE
Issues with groups

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#4293]
Following #3667, I created one group called "Biblio" that builds all the other groups automatically:
<img width="801" alt="capture d ecran 2018-08-25 a 13 10 36" src="https://user-images.githubusercontent.com/15056323/44617719-4d323000-a868-11e8-8f7b-254c1470f793.png">

As you can see in the following picture, it should include all the subgroups, but there is actually no article in "Biblio". Then, I was working on the groups when the "" groups appeared (it has no name...) and I cannot get rid of it. 

<img width="276" alt="capture d ecran 2018-08-25 a 13 12 27" src="https://user-images.githubusercontent.com/15056323/44617731-93878f00-a868-11e8-85d6-1e86c9e4ea9f.png">

I tried on MacOS with 4.3.1 and the last snapshot on the 5.0 from 2018/08/24.

**Comment by PierreMarchand20** [comment]
Yes, several time since it appeared. And I tried with two different versions. I also tried to delete temporary file such as .bib.sav or .bib.bak. Here's the bottom of my .bib file: 
`@Comment{jabref-meta: grouping:
0 AllEntriesGroup:;
1 AutomaticKeywordGroup:Biblio\;2\;groups\;,\;>\;1\;\;\;\;;
}`

**Comment by LinusDietz** [comment]
this should be fixed by now

**Comment by PierreMarchand20** [comment]
I tried with the last version there is still the issue 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/15056323/64381898-8fbe4900-d034-11e9-99ef-b3fde9be7ae6.png">

**Comment by PierreMarchand20** [comment]
Could we reopen this issue ?

**Comment by tobiasdiez** [comment]
Can you please explain how to reproduce this problem, e.g provide a minimal example exhibiting the issue. My guess would be that you have an entry with empty group (or only whitespace as 'a, , b')

**Comment by PierreMarchand20** [comment]
You were right, I had something like `{Foo,Bar,}`. That is strange, I would have thought that the reference with `{Foo,Bar,}` would have been the only one in the group without name. This would have made the search for this reference easier...

But I still do not understand how to use properly groups, in my case I have still this `Biblio` group with 0 items but which is a super group that includes all the automatically created groups... For example, if I take just one reference:
biblio.bib
```
@Article{Test,
  author = {Jean Dupont}
  groups    = {Foo > Bar},
}
```
Then, what do I do in Jabref ?

**Comment by PierreMarchand20** [comment]
The only way I found is to create a group that I set to create a group `Biblio` to automatically create all the groups

<img width="684" alt="image" src="https://user-images.githubusercontent.com/15056323/65395146-24e07200-dd97-11e9-8809-183f1c6e976f.png">

Then, I get
<img width="777" alt="image" src="https://user-images.githubusercontent.com/15056323/65395132-e8147b00-dd96-11e9-8e38-a599bdc52082.png">
where Biblio has zero item, which is quite strange...

PS: I used the old version of Jabref because the last version does not work on my computer (see #5285)

**Comment by PierreMarchand20** [comment]
I confirm that I obtain the same thing with the last dev version

**Comment by bjhamilton** [comment]
Hi! 

I want to combine explicit groups + keywords to create nested groups by keyword, is this possible? For example, if I create a group called TEST_GROUP, but configure JabRef to create groups by keyword field, can I nest my keywords underneath a specific group like ` keyword = {TEST_GROUP:keyword_1;},` (using the colon ':' to nest) ? 

Reason is I like to use keyword groups, but they can get messy if you don't force yourself to be strict with keywords, so what I want is to specify a group like "Neuroscience", but allow the keyword field to nest keywords underneath it which allows me to be "messy" but within a context.

Thanks.
