### ISSUE TITLE
Linked file icon missing

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4530]
JabRef 5.0-dev--snapshot--2018-12-03--master--c94398f4e
Windows 10 10.0 amd64 
Java 1.8.0_172

When I have a PDF with the corresponding `bibtexkey` already in the mapped folder, Jabref **correctly** automatically links the file with the bibtexkey. However, the icon is **missing** in the entry list (see attached screenshot). 

The desired behaviour should be showing an attachment icon as soon as there is a file attachment in the entry list.

![jabref file](https://user-images.githubusercontent.com/10846169/49576466-8c7f1b00-f945-11e8-983e-a2e4f17dcdb3.png)

**Comment by tobiasdiez** [comment]
This should be easy to implement, but we need to be careful about possible performance problems.

**Comment by DOFfactory** [comment]
I am not sure I get it. My issue is that the Jabref automatically detects a linked file (based on bibtexkey) in the File field (as per the screenshot). My only issue is that this detection is not represented in the entry preview. All I want is to have an "attachment" icon in the entry list, I do not think this should need extra computational resources other than with other entry list items. 

I believe this is a bug as it happens only if you already have a PDF file in the folder, and you introduce a New Entry where the bibtexkey = PDF file name. Usually the workflow is the other way around: First new entry and second download PDF file.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by DOFfactory** [comment]
JabRef 5.0-dev--snapshot--2019-05-31--master--f2530da2e
Windows 10 10.0 amd64 
Java 1.8.0_172

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The File Attachment icon does not always appear in Entry 

Steps to reproduce the behavior:
1. Add manually a File to an entry under General
2. The attachment icon does not always appear

![image](https://user-images.githubusercontent.com/10846169/58765343-6d6aea00-8572-11e9-9acf-c9111250ee59.png)
