### ISSUE TITLE
Uncaught exception occured in Thread [JavaFX Application Thread,5,main]

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#4633]
JabRef 5.0-dev--snapshot--2019-02-04--master--a0c2e04ea
Linux 4.15.0-45-generic amd64 
Java 1.8.0_201

JabRef version JabRef 5.0-dev--snapshot--2019-02-04--master--a0c2e04ea on Ubuntu 18.04, maybe related to https://github.com/JabRef/jabref/issues/3431 or https://github.com/JabRef/jabref/issues/4567

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. java -jar -Djavafx.embed.singleThread=true JabRef--master--latest.jar
2. Open [4633.bib.txt](https://github.com/JabRef/jabref/files/2840910/4633.bib.txt)
3. Type "K" in the Searchfield (wait till suggestions)
4. add "a" in the Searchfield (wait till suggestions)
5. Error occurs ![screenshot from 2019-02-07 14-06-58](https://user-images.githubusercontent.com/15687581/52413862-ff8e4480-2ae2-11e9-86c6-ff76ee7615fa.png)
6. But you can ignore the error and just continue working

<details>
  <summary>Terminal Output</summary>
  
  ```bash
14:06:20.128 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/Desktop/4633.bib
14:06:20.933 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
14:06:46.201 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at java.awt.EventQueue$3$1.run(EventQueue.java:714) ~[?:1.8.0_201]
	at com.sun.javafx.application.PlatformImpl.lambda$null$397(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$398(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

  ```
</details>

<details>
  <summary>Uncaught exception occured in Thread [JavaFX Application Thread,5,main]</summary>
  
  ```
java.lang.NullPointerException
	at java.awt.EventQueue$3$1.run(EventQueue.java:714)
	at com.sun.javafx.application.PlatformImpl.lambda$null$397(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$398(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
  ```
</details>

<details>
  <summary>Log Protocoll</summary>
  
  ```
Can only load style files: Preview
Can only load style files: Preview
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
  ```
</details>

**Comment by Siedlerchr** [comment]
This could be related that the SearchWorker is still implemented as SwingWorker and not properly as JavaFX Task. Related of #3861

**Comment by Siedlerchr** [comment]
Refers to #4694

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by JoKalliauer** [comment]
I could reproduce a bug (but not with that easy)
I type several letters (and only sometimes it occurs)

     JabRef 5.0-dev--snapshot--2019-04-02--master--47772fd8c
     Linux 4.15.0-47-generic amd64 
     Java 1.8.0_201


- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists



Steps to reproduce the behavior:
1. java -jar -Djavafx.embed.singleThread=true JabRef--master--latest.jar
2. Open a bib-file
3. Type several time one letters in the Searchfield (wait everytime till suggestions)
4. if it does not occur, restart JabRef and start again do Point 1-3.
5. Error occurs ![Screenshot from 2019-04-03 10-09-16](https://user-images.githubusercontent.com/15687581/55463335-18096f80-55f9-11e9-8443-2fe1dd9cb048.png)
6. But you can ignore the error and just continue working

<details>
  <summary>Terminal Output</summary>
  
  ```bash
jkalliau@jkalliau-Z87M-D3H:~/prgm/JabRef$ java -jar -Djavafx.embed.singleThread=true JabRef--master--latest.jar %U
Ein unbekanntes Format importieren: %U
Fehler beim Öffnen der Datei '%U': Kein passendes Importer gefunden.
10:08:14.199 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
10:08:15.061 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
10:08:22.775 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at java.awt.EventQueue$3$1.run(EventQueue.java:714) ~[?:1.8.0_201]
	at com.sun.javafx.application.PlatformImpl.lambda$null$397(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$398(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]


  ```
</details>

<details>
  <summary>Log Protocoll</summary>
  
  ```
Can only load style files: Preview
Can only load style files: Preview
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
  ```
</details>

**Comment by Siedlerchr** [comment]
Just for your information, you no longer need the  -Djavafx.embed.singleThread=true switch as we now more or less completely removed the old swing stuff.

There have been just some changes merged which could make this obsolete. But please wait until #4840 is resolved

**Comment by krantisaran** [comment]
JabRef 5.1--2020-06-25--d364ffb
Mac OS X 10.15.5 x86_64 
Java 14.0.1

I have just got this error while trying to paste a bib entry into the bib source field. The first time the error box came these were the details:

`java.lang.IndexOutOfBoundsException: [ fromIndex: 2, toIndex: 3, size: 1 ]
	at org.jabref.merged.module@5.1.639/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeListener$Change.getAddedSubList(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.scene.control.behavior.TableViewBehaviorBase.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.callObservers(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ModifiableObservableListBase.add(Unknown Source)
	at java.base/java.util.AbstractList.add(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.scene.control.SelectedCellsMap.add(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.select(Unknown Source)
	at org.jabref/org.jabref.gui.maintable.MainTable.lambda$clearAndSelect$10(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref/org.jabref.gui.maintable.MainTable.clearAndSelect(Unknown Source)
	at org.jabref/org.jabref.gui.maintable.MainTable.lambda$listen$9(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)`

After I closed the error box it appeared again, with these details:

`java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref/org.jabref.gui.maintable.MainTable.getSelectedEntries(Unknown Source)
	at org.jabref/org.jabref.gui.BasePanel.lambda$createMainTable$2(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
	at org.jabref/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.1.639/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.639/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.1.639/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)`

**Comment by zoushucai** [comment]
I had the same problem, 
```
JabRef 5.1--2020-07-01--a336842
Mac OS X 10.14.5 x86_64 
Java 14.0.1
```
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.jabref.merged.module@5.1.742/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at org.jabref.merged.module@5.1.742/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 45 more
Caused by: java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
	at org.jabref.merged.module@5.1.742/org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(Unknown Source)
	at org.jabref.merged.module@5.1.742/org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(Unknown Source)
	at org.jabref@5.1.742/org.jabref.logic.journals.AbbreviationParser.readJournalList(Unknown Source)
	at org.jabref@5.1.742/org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source)
	at org.jabref@5.1.742/org.jabref.logic.journals.AbbreviationParser.readJournalListFromFile(Unknown Source)
	at org.jabref@5.1.742/org.jabref.logic.journals.JournalAbbreviationLoader.readJournalListFromFile(Unknown Source)
	at org.jabref@5.1.742/org.jabref.gui.journals.AbbreviationsFileViewModel.readAbbreviations(Unknown Source)
	at org.jabref@5.1.742/org.jabref.gui.journals.ManageJournalAbbreviationsViewModel.openFile(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.1.742/org.jabref.gui.journals.ManageJournalAbbreviationsViewModel.openFile(Unknown Source)
	at org.jabref@5.1.742/org.jabref.gui.journals.ManageJournalAbbreviationsView.openList(Unknown Source)
	... 55 more
Caused by: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
	at org.jabref.merged.module@5.1.742/org.apache.commons.csv.Lexer.parseEncapsulatedToken(Unknown Source)
	at org.jabref.merged.module@5.1.742/org.apache.commons.csv.Lexer.nextToken(Unknown Source)
	at org.jabref.merged.module@5.1.742/org.apache.commons.csv.CSVParser.nextRecord(Unknown Source)
	... 66 more
```

**Comment by Siedlerchr** [comment]
This seems to be related to the journal abbreviations

**Comment by Siedlerchr** [comment]
@krantisaran  Can you please test again with the latest master?  Note that you can also directly paste the bibtex code on the main table.
@zoushucai  Could you please add some steps what you did`?

**Comment by krantisaran** [comment]
JabRef 5.1--2020-07-06--5e5c137
Mac OS X 10.15.5 x86_64 
Java 14.0.1

I don't get *that* particular error again. However the latest build has caused bug #4877 to come back again with endless cycles, and it did cause this error message which may be related to #4633:

`java.lang.NullPointerException
	at org.jabref@5.1.756/org.jabref.gui.collab.EntryChangeViewModel.makeChange(Unknown Source)
	at org.jabref@5.1.756/org.jabref.gui.collab.ChangeDisplayDialog.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.control.Dialog.setResultAndClose(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.control.DialogPane.lambda$createButton$3(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.1.756/org.jabref.gui.collab.DatabaseChangePane.lambda$onDatabaseChanged$1(Unknown Source)
	at org.jabref.merged.module@5.1.756/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.1.756/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Node.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.control.Button.fire(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.1.756/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)`

**Comment by zoushucai** [comment]
@Siedlerchr  Yes, it does have something to do with journal abbreviations. When I loaded a relatively large journal abbreviation table (the csv file has about 12M), the problem appeared,

**Comment by JoKalliauer** [comment]
Thanks issue is solved in:
```
JabRef 5.2--2020-09-04--3db4313
Linux 5.4.0-42-generic amd64 
Java 14.0.2
```
