### ISSUE TITLE
Import from external database fails for 3.1 and PostgreSQL

### ISSUE THREAD

**Issue by fishforbreakfast** [JabRef/jabref#599]
Hi,

Just tried out 3.1.  Thank you for all of the enhancements, especially the new look!.

I tried to import from an existing database but it failed with the following error in a pop-up window:

"Could not import from SQL database for the following reason:
java.util.ConcurrentModificationException"

There were no obvious command line messages.  I used ./gradlew run to test.

Cheers,

Fred

**Comment by fishforbreakfast** [comment]
I guess I need to look a bit closer or have more coffee.  Here are messages after an attempt to import:
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at net.sf.jabref.sql.importer.DBImporter.performImport(DBImporter.java:108)
        at net.sf.jabref.sql.importer.DbImportAction.performImport(DbImportAction.java:160)
        at net.sf.jabref.sql.importer.DbImportAction.run(DbImportAction.java:131)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at spin.Invocation.evaluate(Invocation.java:175)
        at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
        at java.lang.Thread.run(Thread.java:745)

Hope this helps!

Connect to external database and Export to external database seem to be working, at least as far as not generating error messages.

**Comment by lenhard** [comment]
Thanks, with the stacktrace I can spot the error in the code even without executing it. The following snippet from `DBImporter` (lines 107 - 112) is problematic:
``` java
List<String> colNames = this.readColumnNames(conn);
  for (String next : colNames) {
    if (!columnsNotConsideredForEntries.contains(next)) {
       colNames.add(next);
    }
}
```
The list named `colNames` is modified while iterating over it, hence the `ConcurrentModificationException`. This should be fixable by using a different temporary list and is propably caused by one of my resource usage improvements. We'll notify you when a fix is available for testing!

**Comment by lenhard** [comment]
@fishforbreakfast Could you please check out https://circle-artifacts.com/gh/JabRef/jabref/2214/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-3.2dev--snapshot--2015-12-28--fix-599--372d06d.jar and test if this solves your problem (or alternatively report any errors)?

**Comment by fishforbreakfast** [comment]
Hi,

Thanks for the fix.  It seems to be working, at least with one of my largest reference databases.  I still have the export issue though (issue #473).

Cheers,

Fred

**Comment by lenhard** [comment]
Great! I'll merge this into master then. We'll follow up on the export in #473.

**Comment by fishforbreakfast** [comment]
Thank you very much for the fix!  If I can post more information on #473 I will do so.

Cheers,

Fred
