### ISSUE TITLE
dragging read-only file on entry generates exception

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7072]
JabRef 5.2--2020-11-03--b5bcea4
Linux 5.8.17-200.fc32.x86_64 amd64 
Java 15.0.1

Upon dragging a pdf (without write file permissions) on an entry, I got this exception.

<details>
  <summary>Log File</summary>
  
  ```
java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.2.214/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.214/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.214/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by ilippert** [comment]
another log case for the same error - but without read-only file.

<details>
  <summary>Log File</summary>
  
  ```

java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.2.224/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by ilippert** [comment]
Exception, but file was attached. 
<details>
  <summary>Log File</summary>
  
  ```

java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.2.224/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.224/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by ilippert** [comment]
Same happens regulary - just documenting the errors, in case that is helpful.

JabRef 5.2--2020-11-17--a335f0d
Linux 5.9.8-200.fc33.x86_64 amd64 
Java 15.0.1

<details>
  <summary>Log File</summary>
  
  ```

java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.2.264/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
It's always the same error, so no need to report it everytime, but I fear it's somehow related to javafx. I am not sure if we can do anything about this atm. 
Coul you please give some more information about your GUI toolkit? KDE? GTK? Gnome?
There was a similar thing in OSX which got fixed in the latest javafx application.

**Comment by ilippert** [comment]
Ok, thanks a lot. 
This is gnome, Fedora 33, Wayland.

**Comment by ilippert** [comment]
It is still the same issue
JabRef 5.3--2021-01-07--129abaa
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1

**Comment by Siedlerchr** [comment]
Can you please try again with the latest version? I updated the javafx version

**Comment by ilippert** [comment]
Hi, 
at 
JabRef 5.3--2021-01-09--86852c6
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1 
JavaFX 15.0.1+1

I do not get any reaction - no error message but neither is a pdf attached.

**Comment by ilippert** [comment]
Hi, 

at 
JabRef 5.3--2021-02-03--242a494
Linux 5.10.11-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1
I get

<details>
  <summary>Log File</summary>
  
  ```
java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.3.115/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.115/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.115/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

and the pdf does not get attached.

**Comment by ilippert** [comment]
See also https://gitlab.gnome.org/GNOME/nautilus/-/issues/1745

**Comment by ilippert** [comment]
Hi, 

at 
JabRef 5.3--2021-03-19--049acb9
Linux 5.11.7-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 16+8
I get

<details>
  <summary>Log File</summary>
  
  ```java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.3.203/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.203/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.203/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


  ```
</details>

and the pdf **does** get attached when I drag and drop onto the File field of an entry/in entry editor.

**Comment by Siedlerchr** [comment]
@ilippert  damn, I hoped that the bug was fixed with jfx16 :/
Did you press any modifier key? Can you try with shift/ctrl/alt... And the exception from the log seems to be missing some lines wich state the cause, but that seems like the same as in your other post

**Comment by ilippert** [comment]
Hi, pressing/not pressing modifier keys does not prevent the error message.

     And the exception from the log seems to be missing some lines wich state the cause, but that seems like the same as in your other post 
well that is what JabRef offers to me.

**Comment by ilippert** [comment]
When I attach a file, it does attach, but I get an error in

JabRef 5.3--2021-07-16--c99d61c
Linux 5.13.8-200.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

<details>
  <summary>Log File</summary>
```
java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.3.21/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by ilippert** [comment]
This is the complete error message that JabRef offers to me.

I did not press any keys whilst drag & drop.

**Comment by ilippert** [comment]
error still at JabRef 5.4--2021-08-15--96061b7
Linux 5.13.9-200.fc34.x86_64 amd64 
Java 16.0.2 
JavaFX 16+8

**Comment by Siedlerchr** [comment]
Good news, this might be fixed with the upcoming JavaFX17 version which will be released soon

**Comment by Siedlerchr** [comment]
@ilippert  This will be hopefully fixed in the next master/main version (currently building). Javafx 17 got released and this should fix it.

**Comment by ilippert** [comment]
Hi, 

on 

JabRef 5.4--2021-09-10--6c145fc
Linux 5.13.14-200.fc34.x86_64 amd64 
Java 16.0.2 
JavaFX 17+18

I get this error AND no file gets attached.

```java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.4.182/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.182/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.182/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ilippert** [comment]
JabRef 5.4--2021-09-20--a91420d
Linux 5.13.16-200.fc34.x86_64 amd64 
Java 16.0.2 
JavaFX 17+18

I get this error AND file DOES get attached.


```java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.4.217/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by ilippert** [comment]
JabRef 5.4--2021-09-20--a91420d
Linux 5.13.16-200.fc34.x86_64 amd64 
Java 16.0.2 
JavaFX 17+18

I cannot attach a folder to the entry.


```java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.4.217/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.217/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by CodeDead** [comment]
> It seems like they recognized that this bug is still occuring under linux https://bugs.openjdk.java.net/browse/JDK-8275033

I was facing the same problem for an entirely different project using Fedora Linux 36 and drag and drop events. After a lengthy Reddit discussion, Nir Lisker got this issue reopened. It is still present in JavaFX 19 and below. Hopefully it will gain some traction.

**Comment by philipptempel** [comment]
After updating to JabRef 5.9, I am experiencing the same issue.
When dragging a PDF onto an existing entry, I am receiving an `Uncaught exception occured in Thread[#31,JavaFX Application Thread,5,main]` exception.

**JabRef version**: 5.9
**Operating system**: Ubuntu 22.04.1 LTS 64-bit
**GNOME Version**: GNOME 42.5
**Windowing System**: Wayland
**Kernel**: Linux 5.15.0-58-generic #64-Ubuntu SMP


<details>
<summary>Log File</summary>

```
java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.9.6000/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.9.6000/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

**Comment by CodeDead** [comment]
@philipptempel The issue lies in the JFX SDK and will be fixed in openjfx21, which will be released at an unknown date as of today. It could be months, but it has nothing to do with the application itself

**Comment by ilippert** [comment]
I just checked, in my reading of  https://github.com/openjdk/jfx/commit/7e54b637c9742b8d19c902af21adca9313ba9204 we are now at openjfx22. But the issue has not changed in my experience with JabRef.

JabRef 5.10--2023-07-04--ffedea2
Linux 6.4.8-200.fc38.x86_64 amd64 
Java 21-internal 
JavaFX 20+19

**Comment by Siedlerchr** [comment]
@ilippert  Java & javafx are independent. We are still using javafx 20 as the version number you posted reports :)

**Comment by philipptempel** [comment]
To chime in on the recent activity: I do no longer have the problem / error when dragging files to JabRef. Neither on macOS nor on Linux.

```
JabRef 5.9--2023-01-08--76253f1a7
Mac OS X 13.4.1 x86_64 
Java 19.0.1 
JavaFX 19+11
```

**Comment by ilippert** [comment]
I am on

```
JabRef 5.11--2023-09-25--bc8fb3f
Linux 6.5.5-200.fc38.x86_64 amd64 
Java 21-internal 
JavaFX 20.0.2+3
```

and the issue persists

<details>
  <summary>Log File</summary>
  ```

java.lang.NullPointerException: Cannot read field "dragboard" because "this.this$0.dndGesture" is null
	at org.jabref.merged.module@5.11.201/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at org.jabref.merged.module@5.11.201/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.11.201/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment]
Might be fixed by the newer javafx version, but we are currently blocked by a third party component and cannot upgrade
