### ISSUE TITLE
Customizing entry types clears Optional fields 2 list

### ISSUE THREAD

**Issue by sebschub** [JabRef/jabref#725]
With jabref 3.2, it is reproduced in BibLaTeX mode and otherwise default settings:
1. open "Options > Customize entry types"
2. select entry type "article"
3. add "journal" to to the "Required fields" and press OK
4. open "Options > Customize entry types" again
5. select entry type "article" again

With that, the Optional fields 2 list is empty.

**Comment by stefan-kolb** [comment]
@sebschub Should be fixed in master. Please check http://builds.jabref.org in a few minutes with the new build. Maybe also if all other custom type functionality is still working as expected :smile:

**Comment by dliessi** [comment]
I have this issue again with the following versions:
```
JabRef 4.3.1
Linux 4.17.18-200.fc28.x86_64 amd64 
Java 1.8.0_181
```

**Comment by davidcbenson** [comment]
I hope this is additional information. I am unsure if this is the same problem, but it seems to be. After customizing entries, optional fields will remain available for a single session. If the program closes for any reason, the optional field resets completely to a single optional field, and *returns to the original order*.

I have tried saving, applying then saving, and saving preferences to restore the preferences but nothing works.

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_181

**Comment by Siedlerchr** [comment]
We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by dliessi** [comment]
Sorry for being so late. I have just tested with `JabRef-5.0-dev--snapshot--2018-12-19--master--949d20496.jar` and the problem persists.
I would like to add that the fields in the Optional fields 2 list do not simply disappear, but are moved to the Optional fields list.

**Comment by Siedlerchr** [comment]
I cannot reproduce it. 
1. create a new custom entry type -> `mycustomentrytype` or modify an existing field e.g. article add field `Mittnum`   
2. add some fields
![grafik](https://user-images.githubusercontent.com/320228/50372780-0fa2a100-05d5-11e9-95ee-c3a4b9f0237b.png)
3. save
4. create an entry in entry editor with the new type => All fields are correct listed
5. open customize entry types again  -> Still looks the same

**Comment by dliessi** [comment]
Did you close and reopen JabRef in between?

I get the following:
1. select entry type "article" and click "Default"
2. close and reopen JabRef: all fields lists of entry type "article" still contain the default fields
3. add "abstract" to "Required fields" in "article": both "Optional fields" and "Optional fields 2" contain the default fields, and they still do so if I close and reopen "Customize entry types" without closing JabRef
4. close and reopen JabRef: now "Required fields" still contains the default fields plus "abstract", but all fields of "Optional fields 2" have been moved to "Optional fields", which now contains all default optional fields in a seemingly random order

Tested just now with
```
JabRef-5.0-dev--snapshot--2018-12-19--master--949d20496.jar
Linux 4.19.9-300.fc29.x86_64 (Fedora 29)
Java 1.8.0_181
```

**Comment by LinusDietz** [comment]
good point!

**Comment by calixtus** [comment]
Reimplementing the custom entry types dialog in #5799 by @Siedlerchr has solved this issue. Thanks to him, I think this issue can be closed.
